[rotors]

[rotors.left]
configuration = "I"
starting_position = "A"
ring_setting = "A"

[rotors.middle]
configuration = "II"
starting_position = "A"
ring_setting = "A"

[rotors.right]
configuration = "III"
starting_position = "A"
ring_setting = "A"

[reflector]
configuration = "B"

[plugboard]
configuration = ""